// src/app/not-found.tsx
import { HeroSection } from '@/components/sections/hero-section';
import { Button } from '@/components/ui/button';
import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: '404 - Page Not Found | Spiderly',
  description: "The page you're looking for doesn't exist or has been moved.",
  robots: {
    index: false,
    follow: false,
  },
};

const NotFound = () => {
  return (
    <HeroSection
      title={
        <>
          <span className="text-transparent bg-linear-to-r from-violet-500 to-fuchsia-500 bg-clip-text">
            404
          </span>{' '}
          Page Not Found
        </>
      }
      description="The page you're looking for doesn't exist or has been moved. Let's get you back on track to generating your web apps with Spiderly."
      buttons={
        <>
          <Button asChild>
            <Link href={'/'}>Go to Homepage</Link>
          </Button>
        </>
      }
    />
  );
};

export default NotFound;

// src/app/pages/not-found/not-found.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { CommonModule } from '@angular/common';
import { SectionWrapperComponent } from '../../components/section-wrapper/section-wrapper.component';
import { ButtonModule } from 'primeng/button';
import { Meta, Title } from '@angular/platform-browser';

@Component({
  selector: 'app-not-found',
  imports: [RouterLink, CommonModule, SectionWrapperComponent, ButtonModule],
  templateUrl: './not-found.component.html',
})
export class NotFoundComponent {
  constructor(
    private titleService: Title,
    private metaService: Meta,
  ) {
    this.titleService.setTitle('404 Page Not Found | Spiderly');
    this.metaService.updateTag({
      name: 'description',
      content:
        "The page you're looking for doesn't exist. Return to the Spiderly homepage to generate your .NET (C#) + Angular web app.",
    });
    this.metaService.updateTag({ name: 'robots', content: 'noindex, nofollow' });
  }
}

<app-section-wrapper backgroundColor="dark" textAlign="center">
  <div>
    <h1 style="margin-bottom: 15px">
      <div class="gradient-title">404</div>
      <div class="title">Page Not Found</div>
    </h1>
    <div class="text-below-title" style="margin-bottom: 30px">
      The page you're looking for doesn't exist or has been moved. Let's get you back on track to
      generating your web apps with Spiderly.
    </div>
    <div>
      <p-button [routerLink]="['/']" label="Go to Homepage"></p-button>
    </div>
  </div>
</app-section-wrapper>
