// src/app/components/homepage/hero/hero.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SectionWrapperComponent } from "../../section-wrapper/section-wrapper.component";

@Component({
  selector: 'app-hero',
  templateUrl: './hero.component.html',
  styleUrl: './hero.component.scss',
  standalone: true,
  imports: [CommonModule, SectionWrapperComponent]
})
export class HeroComponent {
  terminalMessages: string[] = [
    "spiderly init",
    "App name without spaces: SpiderlyTestApp",
    "Template type (blank/loyalty/invertory management): blank",
    "Basic app structure created, now you can use Spiderly to generate the rest of the app!",
  ];
}

<app-section-wrapper>
  <div style="flex: 1;">
    <h1 style="margin-bottom: 15px;">
      <div class="gradient-title">Build Apps.</div>
      <div class="title">Fast.</div>
    </h1>
    <div class="text-below-title">
      Generate front-end and back-end CRUD operations code from C# classes, with
      full customization. Code updates automatically with every class change at
      the right place in the project.
    </div>
  </div>
  <div class="background-transparent-gradient" style="flex: 1;">
    <div class="terminal-wrapper">
      <div style="margin-bottom: 1rem; display: flex;">
        <div class="terminal-circle" style="background-color: #EC4899;"></div>
        <div class="terminal-circle" style="background-color: #FBBF24; margin-left: 1rem;"></div>
        <div class="terminal-circle" style="background-color: #10B981; margin-left: 1rem;"></div>
      </div>
      @for (message of terminalMessages; track $index) {
        <code style="margin-top: 1rem; display: flex;">
            <span style="color: #f170b1;">$</span>
            <span class="terminal-message">
                {{message}}
                <br />
            </span>
        </code>
      }
    </div>
  </div>
</app-section-wrapper>

// src/components/Hero.tsx
import { HomepageSectionWrapper } from "./HomepageSectionWrapper";

const cliMessages = [
  "spiderly init",
  "App name without spaces: SpiderlyTestApp",
  "Template type (blank/loyalty/invertory management): blank",
  "Basic app structure created, now you can use Spiderly to generate the rest of the app!",
];

export const Hero = () => (
  <HomepageSectionWrapper color="bg-gray-900">
    <div className="pb-6 pr-6">
      <h1>
        <div className="text-5xl md:text-7xl font-bold py-1 inline-block text-wrap md:text-nowrap bg-gradient-to-r from-pink-600 to-yellow-300 text-transparent bg-clip-text">
          Build Apps.
        </div>
        <div className="text-5xl md:text-7xl font-bold py-1 mb-2">Fast.</div>
      </h1>
      <div className="text-lg md:text-xl py-1 text-gray-400">
        Generate front-end and back-end CRUD operations code from C# classes,
        with full customization. Code updates automatically with every class
        change at the right place in the project.
      </div>
    </div>
    <div className="w-full bg-linear-to-br from-50% to-pink-900 pb-6 pr-6 rounded-lg">
      <div
        className="coding inverse-toggle px-5 pt-4 shadow-lg text-gray-300 text-sm font-mono subpixel-antialiased 
                        bg-gray-800 pb-6 rounded-lg leading-normal overflow-hidden"
      >
        <div className="top mb-2 flex">
          <div className="h-3 w-3 bg-pink-500 rounded-full"></div>
          <div className="ml-2 h-3 w-3 bg-yellow-300 rounded-full"></div>
          <div className="ml-2 h-3 w-3 bg-green-500 rounded-full"></div>
        </div>
        {cliMessages.map((msg, index) => (
          <div key={index} className="mt-4 flex">
            <span className="text-pink-400">$</span>
            <p className="flex-1 typing items-center pl-2">
              {msg}
              <br />
            </p>
          </div>
        ))}
      </div>
    </div>
  </HomepageSectionWrapper>
);
